### ISSUE TITLE
manifest update generates a Export-Package on a single line

### ISSUE THREAD

**Issue by dvojtise** [gemoc/gemoc-studio#35]
_From @awortmann on March 14, 2017 15:23_

when updating the manifest, melange generates a package export-package entry on a single line, this is fine for small projects, but creates invalid manifest files when there are a lot exported packages ...

_Copied from original issue: diverse-project/melange#71_

**Comment by dvojtise** [comment]
_From @fcoulon on March 14, 2017 16:35_

Seems related to GemocSequentialLanguageBuilder.

@dvojtise 
Maybe we need to manage Export-packages here ?
https://github.com/diverse-project/tools/blob/master/commons-eclipse/fr.inria.diverse.commons.eclipse.pde/src/fr/inria/diverse/commons/eclipse/pde/manifest/ManifestChanger.java#L62

**Comment by dvojtise** [comment]
Yes indeed

may be this is also the place of the problem that occurs on some system that double the line break in the require-bundle, it should use the system separator in all the file.

**Comment by dvojtise** [comment]
should be fixed with latest version of DiverSE commons

**Comment by fcoulon** [comment]
From org.eclipse.pde.internal.ui.editor.actions.FormatOperation
There is the command called by Ctrl+Shift+F in the Manifest editor :
`public static void format(IFile file, IProgressMonitor mon)`

It can be helpful if we have other bugs in the future.
