### ISSUE TITLE
[Concurrent] Breakpoint on MSE cannot work for multiple reasons (see details)

### ISSUE THREAD

**Issue by Gwend4l** [gemoc/gemoc-studio#41]
In concurrent mode, in the "Stimuli manager" view, there is the possibility to add a breakpoint on an MSE. This break will never happen.

With the current code, this will never work for two reasons:
- This stores a breakpoint for the timesquare object "fr.inria.aoste.timesquare.ecl.feedback.feedback.impl.ModelSpecificEventImpl", and not for the corresponding GEMOC object "fr.inria.diverse.trace.commons.model.trace.MSE"
- The concurrent debugger only calls `shouldBreak` on the starting `Step`, and never on the `MSEOccurrence` that may trigger this step

To fix this problem, we must find the underlying MSE when creating breakpoints, and we must fix how breakpoints are checked in concurrent mode.

**Comment by ebousse** [comment]
Ups, created the issue with the wrong github account. I wonder if an issue can be deleted.
