### ISSUE TITLE
Problem at runtime-Eclipse applicatin，K3dsa call Scilab 

### ISSUE THREAD

**Issue by JoyeGCL** [gemoc/gemoc-studio#62]
Hi, GEMOC TEAM
      In modeling workbench，when I debug, the runtime shutdown since I call Scilab in k3dsa xtend file. It tells me that if Scilab is used form java, make sure that your IDE(ex:Netbeans, etc)is not adding extra dependencies which could not be found at runtime. Then the runtime shutdown.
![error](https://user-images.githubusercontent.com/22368519/35729221-00748d18-0849-11e8-8e0c-ec6e72737e59.png)
    In the first language workbench Console, it tells me that You cannot read the Main Scilab class.Some errors occurred while loading the Java library.This can lead to incorrect behavior.Please check the SCI /etc/ classpath.xml
![console](https://user-images.githubusercontent.com/22368519/35729357-53ee8548-0849-11e8-852f-3a4c9de9b721.png)
    Look forward to your reply.

**Comment by dvojtise** [comment]
Hi, not sure this is a gemoc related issue

are you able to correctly run your scilab code from a standard eclipse plugin ? 
if so, are you sure that the project generated by melange has the correct dependencies too ? (the project generated by melange copies the k3 code, so it must have all the dependencies too)

**Comment by JoyeGCL** [comment]
Hi dvojtise,
   It's ok when I test my testcallscilab.xtend file in the new Eclipse Application(modeling workbench), I can right click the xtend file and run as Java Application. The xtend code do call scilab successfully.
  However, when I debug my model, I right click the global context, choose Step Into, then a warning box tells that  if Scilab is used form java, make sure that your IDE(ex:Netbeans, etc) is not adding extra dependencies which could not be found at runtime. Then the modeling workbench shutdown.
  And in the first language workbench Console, it tells me that You cannot read the Main Scilab class. Some errors occurred while loading the Java library. This can lead to incorrect behavior. Please check the SCI /etc/ classpath.xml

**Comment by dvojtise** [comment]
"run as Java Application" is NOT the same as running as a plugin/OSGI. The classpath is not built the same way.

To test that you can call scilab in the correct Plugin/OSGI mode, please first try to create a simple UI plugin in your first workbench (File > new Plugin project > next > choose a template, I suggest "Hello world command" ) in this plugin make sure to add all required dependencies (to the k3 project and scilab plugins and jars).
 
**Important**: the project classpath must NOT be modified directly, you can modify only the manifest.MF/plugin.xml

launch the second eclipse , and try your button.

If this works, then try to reproduce the manifest to projects containing the melange files *and* in the project generated by melange (ie. org.joye.xfsmode.xfsmode in you case)

**Comment by JoyeGCL** [comment]
Hi dvojtise,
Thank you so much for your suggestion. I have known that I didn't set scilab jar in classpath in Runtime and I made some try.

Following your suggestion, I test call scilab in a plug-in project. But since I am not familiar with plug-in, there is still something wrong. The following is steps of my small test project, maybe you can point out some mistakes.

Firstly, I test java1 project(Java project),  run as>Java Application, it's ok to call scilab and I can get the result in console.

PS. To call scilab, I have to set some system variables in my laptop.
   Classpath=.;%JAVA_HOME%\lib;%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar;C:\Program Files\scilab-6.0.1\modules\javasci\jar\org.scilab.modules.javasci.jar;C:\Program Files\scilab-6.0.1\modules\types\jar\org.scilab.modules.types.jar
   Path=C:\ProgramData\Oracle\Java\javapath;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%JAVA_HOME%\bin;%JAVA_HOME%\jre\bin;C:\Program Files\scilab-6.0.1\bin
  SCI=C:\Program Files\scilab-6.0.1
 
**Here,the path to the native library libjavasci.dll and to its dependencies must be added in the PATH environment variable. All the needed libraries are in the "bin" folder.**


![javacallscilab](https://user-images.githubusercontent.com/22368519/36959425-e421184c-207c-11e8-8e28-3c14fd4c7025.png)

Secondly,

- I create a plugin project plugin1, choose "Hello world command" template.

- plugin1, right click, new folder lib, add three jars about calling scilab.

- In MANIFEST.MF>Runtime, Classpath, I add the jar from lib.
![add classpath](https://user-images.githubusercontent.com/22368519/36959887-6ad35042-207f-11e8-8c91-67b0002f8129.png)

![manifest mf](https://user-images.githubusercontent.com/22368519/36959836-28cb5924-207f-11e8-9e77-32b278d65a56.png)

- add call scilab code in SampleHandler.java like the picture
![add scilab code](https://user-images.githubusercontent.com/22368519/36959834-247d9fd0-207f-11e8-9e53-117afdba1777.png)

- launch the second eclipse application
![second eclipse application](https://user-images.githubusercontent.com/22368519/36959848-399f4382-207f-11e8-80c9-d7770003acc5.png)

- click the sample menu, the hello is shown , but the result should be called from scilab is not shown in console.
![java console wrong](https://user-images.githubusercontent.com/22368519/36959865-4b00cc40-207f-11e8-8563-8fa5018b3286.png)


![touch sample menu](https://user-images.githubusercontent.com/22368519/36959854-3ea9a1c4-207f-11e8-95c5-27c6397192b2.png)
![touch sample menu2](https://user-images.githubusercontent.com/22368519/36959855-415c957a-207f-11e8-952a-5ab7fa044a66.png)
![plugin console wrong](https://user-images.githubusercontent.com/22368519/36959896-78cef94e-207f-11e8-9417-256ffa0a16d4.png)

I think it is due to the path C:\Program Files\scilab-6.0.1\bin I didn't set in plugin project, so it can not find related jars.
where should I set ? In Environment when launch? or the error is caused by other reasons.

Look forward to your reply.
